# Generated by Django 3.2.25 on 2025-12-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_river'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='miles',
            field=models.FloatField(),
        ),
    ]
