# Generated by Django 3.2.25 on 2026-01-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_river_miles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='river',
            old_name='user',
            new_name='owner',
        ),
    ]
